#!/usr/bin/env python
"""
Test script to verify WeasyPrint installation and basic PDF generation
"""
import os
import sys
import django

# Setup Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

def test_weasyprint():
    """Test WeasyPrint installation"""
    try:
        from weasyprint import HTML, CSS
        print("✅ WeasyPrint imported successfully")
        
        # Test basic HTML to PDF conversion
        html_content = """
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <title>Test PDF</title>
            <style>
                body { font-family: Arial, sans-serif; }
                h1 { color: #007bff; }
            </style>
        </head>
        <body>
            <h1>Test PDF Generation</h1>
            <p>This is a test PDF generated by WeasyPrint.</p>
        </body>
        </html>
        """
        
        html = HTML(string=html_content)
        pdf = html.write_pdf()
        
        # Save test PDF
        with open('test_output.pdf', 'wb') as f:
            f.write(pdf)
            
        print("✅ PDF generated successfully: test_output.pdf")
        print(f"📄 PDF size: {len(pdf)} bytes")
        
        return True
        
    except ImportError as e:
        print(f"❌ WeasyPrint import failed: {e}")
        print("💡 Install with: pip install weasyprint")
        return False
        
    except Exception as e:
        print(f"❌ PDF generation failed: {e}")
        return False

if __name__ == "__main__":
    print("🧪 Testing WeasyPrint PDF generation...")
    success = test_weasyprint()
    
    if success:
        print("\n🎉 WeasyPrint is working correctly!")
    else:
        print("\n🚨 WeasyPrint test failed. Check the error messages above.")
