"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os, random, string, inspect
from pathlib import Path
from dotenv import load_dotenv
from str2bool import str2bool

load_dotenv()  # take environment variables from .env.

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'Super_Secr3t_9999')

# Enable/Disable DEBUG Mode
DEBUG = str2bool(os.environ.get('DEBUG', 'True'))
#print(' DEBUG -> ' + str(DEBUG) ) 

ALLOWED_HOSTS = ['*']

# Add here your deployment HOSTS
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000', 
    'http://localhost:5085', 
    'http://127.0.0.1:8000', 
    'http://127.0.0.1:5085',
    'http://localhost:8094',    # Your current port
    'http://127.0.0.1:8094',   # Your current port
    'http://localhost:3000',    # React/Next.js
    'http://127.0.0.1:3000',   # React/Next.js
    'http://localhost:4200',    # Angular
    'http://127.0.0.1:4200',   # Angular
    'http://localhost:5173',    # Vite
    'http://127.0.0.1:5173',   # Vite
    'http://84.247.171.243:9494',  # Your production server
    'https://84.247.171.243:9494', # HTTPS version
]

X_FRAME_OPTIONS = "SAMEORIGIN"

RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:    
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    "django.contrib.admin",
    'admin_datta.apps.AdminDattaConfig',
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Serve UI pages
    "apps.pages",

    # Dynamic DT
    "apps.dyn_dt",

    # Dynamic API
    "apps.dyn_api",

    # Charts
    "apps.charts",

    # Vehicle Rental Management
    "apps.vehicle_rental",

    # Tooling API-GEN
    'rest_framework',            # Include DRF           # <-- NEW 
    'rest_framework.authtoken',  # Include DRF Auth      # <-- NEW   
    'drf_yasg',                 # Include DRF Swagger   # <-- NEW  
    'corsheaders',              # CORS headers          # <-- NEW
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",        # <-- CORS middleware (must be early)
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "config.middleware.SessionTimeoutMiddleware",   # <-- Custom session timeout middleware (after auth)
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

HOME_TEMPLATES = os.path.join(BASE_DIR, 'templates') 

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [HOME_TEMPLATES],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DB_ENGINE   = os.getenv('DB_ENGINE'   , None)
DB_USERNAME = os.getenv('DB_USERNAME' , None)
DB_PASS     = os.getenv('DB_PASS'     , None)
DB_HOST     = os.getenv('DB_HOST'     , None)
DB_PORT     = os.getenv('DB_PORT'     , None)
DB_NAME     = os.getenv('DB_NAME'     , None)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db', 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

#if not DEBUG:
#    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'  # Redirect to login page when login required

# EMAIL CONFIGURATION
# Para desenvolvimento (emails no console) descomente a linha abaixo:
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Para enviar emails reais (Gmail - substitua com suas credenciais):
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'adylsonrtb08@gmail.com'  # Substitua pelo seu email
EMAIL_HOST_PASSWORD = 'quik juts iqfx inxk'  # Substitua pela senha de app do Gmail
DEFAULT_FROM_EMAIL = 'adylsonrtb08@gmail.com'
EMAIL_TIMEOUT = 10

# ### DYNAMIC_DATATB Settings ###
DYNAMIC_DATATB = {
    # SLUG -> Import_PATH 
    'product'  : "apps.pages.models.Product",
    'vehicle'  : "apps.vehicle_rental.models.Vehicle",
    'customer' : "apps.vehicle_rental.models.Customer",
    'rental'   : "apps.vehicle_rental.models.Rental",
    'expense'  : "apps.vehicle_rental.models.Expense",
    'maintenance' : "apps.vehicle_rental.models.MaintenanceRecord",
}
########################################

# Syntax: URI -> Import_PATH
DYNAMIC_API = {
    # SLUG -> Import_PATH 
    'product'  : "apps.pages.models.Product",
    'vehicle'  : "apps.vehicle_rental.models.Vehicle",
    'customer' : "apps.vehicle_rental.models.Customer",
    'rental'   : "apps.vehicle_rental.models.Rental",
    'expense'  : "apps.vehicle_rental.models.Expense",
    'maintenance' : "apps.vehicle_rental.models.MaintenanceRecord",
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
}

# Swagger settings
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Token': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'USE_SESSION_AUTH': True,
    'JSON_EDITOR': True,
    'SUPPORTED_SUBMIT_METHODS': [
        'get',
        'post',
        'put',
        'delete',
        'patch'
    ],
    'OPERATIONS_SORTER': 'alpha',
    'TAGS_SORTER': 'alpha',
    'DOC_EXPANSION': 'none',
    'DEEP_LINKING': True,
    'SHOW_EXTENSIONS': True,
    'SHOW_COMMON_EXTENSIONS': True,
}

REDOC_SETTINGS = {
   'LAZY_RENDERING': False,
}

# Session Configuration
SESSION_COOKIE_AGE = 30 * 60  # 30 minutes in seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True  # Refresh session on every request
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_COOKIE_SAMESITE = 'Lax'

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",    # React default
    "http://127.0.0.1:3000",   # React default
    "http://localhost:3001",    # React alternative
    "http://127.0.0.1:3001",   # React alternative
    "http://localhost:4200",    # Angular default
    "http://127.0.0.1:4200",   # Angular default
    "http://localhost:5173",    # Vite default
    "http://127.0.0.1:5173",   # Vite default
    "http://localhost:8080",    # Vue default
    "http://127.0.0.1:8080",   # Vue default
    "http://localhost:8000",    # Django default
    "http://127.0.0.1:8000",   # Django default
    "http://localhost:8094",    # Your current Django port
    "http://127.0.0.1:8094",   # Your current Django port
    "http://84.247.171.243:9494",  # Your production server
    "https://84.247.171.243:9494", # HTTPS version
]

# Allow all origins during development (WARNING: Don't use in production!)
CORS_ALLOW_ALL_ORIGINS = True

# Allow credentials to be included in CORS requests
CORS_ALLOW_CREDENTIALS = True

# Headers that can be used during the actual request
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Methods that can be used during the actual request
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Allow the Authorization header
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://\w+\.netlify\.app$",
    r"^https://\w+\.vercel\.app$",
    r"^https://\w+\.herokuapp\.com$",
]
########################################
