# Generated by Django 4.2.9 on 2025-07-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rental', '0002_alter_vehicle_chassis_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='maintenance_type',
            field=models.CharField(choices=[('scheduled', 'Manutenção Programada'), ('repair', 'Reparação'), ('inspection', 'Inspeção'), ('warranty', 'Trabalho de Garantia'), ('accident', 'Reparação de Acidente')], max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendado'), ('in_progress', 'Em Progresso'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('active', 'Ativo'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Gasolina'), ('diesel', 'Diesel'), ('electric', 'Eléctrico'), ('hybrid', 'Híbrido'), ('lpg', 'GPL')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='gearbox_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automática'), ('cvt', 'CVT'), ('semi_automatic', 'Semi-Automática')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('available', 'Disponível'), ('rented', 'Alugado'), ('maintenance', 'Em Manutenção'), ('retired', 'Retirado')], default='available', max_length=20),
        ),
    ]
