# Generated by Django 4.2.9 on 2025-07-28 19:33

import apps.vehicle_rental.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle_rental', '0003_alter_maintenancerecord_maintenance_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='RentalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('start_exterior_front', 'Inicial - Exterior Frente'), ('start_exterior_back', 'Inicial - Exterior Traseira'), ('start_exterior_left', 'Inicial - Exterior Esquerda'), ('start_exterior_right', 'Inicial - Exterior Direita'), ('start_interior_front', 'Inicial - Interior Frente'), ('start_interior_back', 'Inicial - Interior Traseira'), ('start_dashboard', 'Inicial - Painel'), ('start_damage', 'Inicial - Danos Existentes'), ('return_exterior_front', 'Devolução - Exterior Frente'), ('return_exterior_back', 'Devolução - Exterior Traseira'), ('return_exterior_left', 'Devolução - Exterior Esquerda'), ('return_exterior_right', 'Devolução - Exterior Direita'), ('return_interior_front', 'Devolução - Interior Frente'), ('return_interior_back', 'Devolução - Interior Traseira'), ('return_dashboard', 'Devolução - Painel'), ('return_damage', 'Devolução - Novos Danos'), ('return_fuel_gauge', 'Devolução - Medidor Combustível')], max_length=30)),
                ('image', models.ImageField(upload_to=apps.vehicle_rental.models.rental_photo_upload_path)),
                ('description', models.TextField(blank=True, help_text='Opcional: Descreva detalhes específicos', null=True)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='vehicle_rental.rental')),
                ('taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rental Photo',
                'verbose_name_plural': 'Rental Photos',
                'ordering': ['taken_at'],
                'indexes': [models.Index(fields=['rental'], name='vehicle_ren_rental__4dcba1_idx'), models.Index(fields=['photo_type'], name='vehicle_ren_photo_t_f6f9b9_idx'), models.Index(fields=['taken_at'], name='vehicle_ren_taken_a_9fcb74_idx')],
                'unique_together': {('rental', 'photo_type')},
            },
        ),
    ]
