# Generated by Django 4.2.9 on 2025-07-31 00:28

import apps.vehicle_rental.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rental', '0004_alter_customer_country_rentalphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(blank=True, help_text='Vehicle photo (optional)', null=True, upload_to=apps.vehicle_rental.models.vehicle_photo_upload_path),
        ),
    ]
