# Generated by Django 4.2.9 on 2025-10-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rental', '0006_alter_rental_commission_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.TextField(blank=True, help_text='Additional description or notes about the vehicle', null=True),
        ),
    ]
