# Generated by Django 4.2.9 on 2025-11-17 07:55

import apps.vehicle_rental.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle_rental', '0008_add_rental_evaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Vehicle photo', upload_to=apps.vehicle_rental.models.vehicle_additional_photo_upload_path)),
                ('photo_type', models.CharField(choices=[('exterior_front', 'Exterior - Front'), ('exterior_back', 'Exterior - Back'), ('exterior_left', 'Exterior - Left Side'), ('exterior_right', 'Exterior - Right Side'), ('interior_dashboard', 'Interior - Dashboard'), ('interior_seats', 'Interior - Seats'), ('interior_trunk', 'Interior - Trunk'), ('engine', 'Engine'), ('documents', 'Documents'), ('damage', 'Damage/Issue'), ('other', 'Other')], default='other', help_text='Type/category of this photo', max_length=30)),
                ('title', models.CharField(blank=True, help_text='Optional title or description for this photo', max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as primary photo for this vehicle')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded this photo', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(help_text='Vehicle this photo belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='additional_photos', to='vehicle_rental.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Photo',
                'verbose_name_plural': 'Vehicle Photos',
                'ordering': ['-is_primary', 'photo_type', '-uploaded_at'],
                'indexes': [models.Index(fields=['vehicle'], name='vehicle_ren_vehicle_d05aa7_idx'), models.Index(fields=['photo_type'], name='vehicle_ren_photo_t_81a973_idx'), models.Index(fields=['is_primary'], name='vehicle_ren_is_prim_774fc2_idx'), models.Index(fields=['uploaded_at'], name='vehicle_ren_uploade_59f66c_idx')],
            },
        ),
    ]
