# Generated by Django 4.2.9 on 2026-02-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rental', '0010_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='assento_crianca',
            field=models.BooleanField(default=False, help_text='Necessita de assento de criança'),
        ),
        migrations.AddField(
            model_name='rental',
            name='motorista',
            field=models.BooleanField(default=False, help_text='Necessita de motorista'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(default='Portugal', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Gasóleo'), ('diesel', 'Diesel'), ('electric', 'Eléctrico'), ('hybrid', 'Híbrido'), ('lpg', 'GPL'), ('gas', 'Gasolina')], max_length=20),
        ),
    ]
