# Generated by Django 4.2.9 on 2026-02-08 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rental', '0011_rental_assento_crianca_rental_motorista_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='assento_crianca',
            new_name='car_seat',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='motorista',
            new_name='driver',
        ),
    ]
