# Generated by Django 4.2.9 on 2026-02-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rental', '0013_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='otp',
            field=models.CharField(blank=True, help_text='One-time password for password recovery', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when OTP was created', null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
