# Generated by Django 4.2.9 on 2026-02-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rental', '0014_customer_otp_customer_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='car_seat_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Taxa adicional de assento criança por dia (500 ECV)', max_digits=8),
        ),
        migrations.AddField(
            model_name='rental',
            name='driver_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Taxa adicional de motorista por dia (3000 ECV)', max_digits=8),
        ),
        migrations.AddField(
            model_name='rental',
            name='pickup_location',
            field=models.CharField(blank=True, help_text='Local de entrega do veículo', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='return_location',
            field=models.CharField(blank=True, help_text='Local de devolução do veículo', max_length=200, null=True),
        ),
    ]
