# Generated by Django 4.2.9 on 2026-02-24 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle_rental', '0015_rental_car_seat_fee_rental_driver_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do local (ex: Aeroporto Amílcar Cabral, Hotel Pestana, etc.)', max_length=200)),
                ('address', models.TextField(blank=True, help_text='Endereço completo do local', null=True)),
                ('location_type', models.CharField(choices=[('pickup', 'Local de Entrega'), ('return', 'Local de Devolução'), ('both', 'Entrega e Devolução')], default='both', help_text='Tipo de operação no local', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Informações adicionais sobre o local', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Local ativo para uso')),
                ('default_pickup', models.BooleanField(default=False, help_text='Local padrão para entrega')),
                ('default_return', models.BooleanField(default=False, help_text='Local padrão para devolução')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Local de Entrega/Devolução',
                'verbose_name_plural': 'Locais de Entrega/Devolução',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='vehicle_ren_is_acti_02139d_idx'), models.Index(fields=['location_type'], name='vehicle_ren_locatio_c140ee_idx')],
            },
        ),
    ]
