# Generated by Django 4.2.9 on 2026-02-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rental', '0016_deliverylocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='license_issue_date',
            field=models.DateField(blank=True, help_text='Data de emissão da carta de condução', null=True),
        ),
    ]
