# Generated by Django 4.2.9 on 2026-02-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rental', '0017_customer_license_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Data de nascimento do cliente', null=True),
        ),
    ]
