# Generated by Django 4.2.9 on 2026-02-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rental', '0018_customer_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(help_text='Data de nascimento do cliente'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='license_issue_date',
            field=models.DateField(help_text='Data de emissão da carta de condução'),
        ),
    ]
