# Generated by Django 4.2.9 on 2026-02-27 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rental', '0019_alter_customer_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='pickup_location',
            field=models.ForeignKey(blank=True, help_text='Local de entrega do veículo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_rentals', to='vehicle_rental.deliverylocation'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='return_location',
            field=models.ForeignKey(blank=True, help_text='Local de devolução do veículo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_rentals', to='vehicle_rental.deliverylocation'),
        ),
    ]
