# Generated by Django 4.2.9 on 2026-03-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rental', '0020_alter_rental_pickup_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='description_en',
            field=models.TextField(blank=True, help_text='Description in English (auto-translated)', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='description_fr',
            field=models.TextField(blank=True, help_text='Description in French (auto-translated)', null=True),
        ),
    ]
