# Generated by Django 4.2.9 on 2026-03-01 13:19

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle_rental', '0021_add_vehicle_translations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Taxa de serviço em percentual (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('driver_daily_rate', models.DecimalField(decimal_places=2, default=Decimal('3000.00'), help_text='Valor diário para motorista em CVE', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('car_seat_daily_rate', models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Valor diário para assento de criança em CVE', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('euro_exchange_rate', models.DecimalField(decimal_places=4, default=Decimal('110.2650'), help_text='Taxa de câmbio EUR/CVE', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('usd_exchange_rate', models.DecimalField(decimal_places=4, default=Decimal('101.0000'), help_text='Taxa de câmbio USD/CVE', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Último usuário que atualizou as configurações', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
    ]
