# Generated by Django 4.2.9 on 2026-03-01 13:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rental', '0022_add_system_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='service_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taxa de serviço em valor fixo (CVE). Deixar vazio se usar percentual.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='service_fee_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taxa de serviço em percentual (0-100%). Deixar vazio se usar valor fixo.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
    ]
