# Generated by Django 4.2.9 on 2026-03-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rental', '0023_update_service_fee_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='currency',
            field=models.CharField(choices=[('CVE', 'Cabo Verde Escudo (CVE)'), ('EUR', 'Euro (EUR)'), ('USD', 'US Dollar (USD)')], default='CVE', help_text='Moeda utilizada no aluguer', max_length=3),
        ),
    ]
