# Generated by Django 4.2.9 on 2026-03-21 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle_rental', '0024_add_currency_to_rental'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('rental_confirmation', 'Confirmação de Aluguer'), ('rental_cancellation', 'Cancelamento de Aluguer'), ('rental_reminder', 'Lembrete de Aluguer'), ('payment_confirmation', 'Confirmação de Pagamento'), ('other', 'Outro')], default='other', help_text='Tipo de notificação', max_length=50)),
                ('recipient_email', models.EmailField(help_text='Email do destinatário', max_length=254)),
                ('subject', models.CharField(help_text='Assunto do email', max_length=255)),
                ('content', models.TextField(help_text='Conteúdo em texto simples')),
                ('html_content', models.TextField(blank=True, help_text='Conteúdo HTML do email', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('failed', 'Falhou')], default='pending', help_text='Estado do envio', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Mensagem de erro (se falhou)', null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0, help_text='Número de tentativas de envio')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Data de envio bem-sucedido', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Utilizador que criou/reenviou', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Cliente destinatário da notificação', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='vehicle_rental.customer')),
                ('rental', models.ForeignKey(blank=True, help_text='Aluguer relacionado (se aplicável)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='vehicle_rental.rental')),
            ],
            options={
                'verbose_name': 'Customer Notification',
                'verbose_name_plural': 'Customer Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='vehicle_ren_status_e6fcf7_idx'), models.Index(fields=['notification_type'], name='vehicle_ren_notific_89718a_idx'), models.Index(fields=['created_at'], name='vehicle_ren_created_1a682e_idx'), models.Index(fields=['customer', 'status'], name='vehicle_ren_custome_37e836_idx')],
            },
        ),
    ]
